# Generated by Django 2.1 on 2018-08-27 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Ciudad')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Servicio')),
                ('usuario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Usuario')),
            ],
        ),
    ]
