# Generated by Django 2.1 on 2018-08-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20180827_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_servicio',
            name='observaciones',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
